version: '3.5'

services:

  insly_nginx:
    container_name: insly_nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    working_dir: /var/www
    volumes:
      - ./src/1:/var/www/0
      - ./src/1:/var/www/1
      - ./src/2:/var/www/2
      - ./src/3:/var/www/3
    ports:
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8081:81"
      - "127.0.0.1:8082:82"
      - "127.0.0.1:8083:83"
    networks:
      - default
    depends_on:
      - insly_php

  insly_php:
    container_name: insly_php
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /var/www
    volumes:
      - ./src:/var/www:cached
    ports:
      - "127.0.0.1:9009:9000"
    networks:
      - default
    depends_on:
      - insly_db

  insly_db:
    container_name: insly_db
    image: mysql:5.7.24
    working_dir: /var/www
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - insly_dbdata:/var/lib/mysql:cached
      - ./:/var/www:cached
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "127.0.0.1:3366:3306"
    networks:
      - default

volumes:
  insly_dbdata:
  insly_php:

networks:
  default:
    driver: bridge
    name: insly